### ISSUE TITLE
error in ioBroker Adapter since today

### ISSUE THREAD

**Issue by Moormerlander** [axelmohnen/fhem-landroid-s#6]
Hi there,

since today i get this errors when starting the adapter in ioBroker:

`
landroid-s.0 | 2019-04-08 12:54:02.398 | info | cleaned everything up...
-- | -- | -- | --
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at _combinedTickCallback (internal/process/next_tick.js:80:11)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at endReadableNT (_stream_readable.js:974:12)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at IncomingMessage.emit (events.js:185:7)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at emitNone (events.js:91:20)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.landroid-s/lib/mqttCloud.js:278:45)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | at Object.parse (native)
landroid-s.0 | 2019-04-08 12:54:02.396 | error | SyntaxError: Unexpected token N in JSON at position 0
landroid-s.0 | 2019-04-08 12:54:02.393 | error | uncaught exception: Unexpected token N in JSON at position 0
landroid-s.0 | 2019-04-08 12:54:01.930 | info | starting. Version 2.5.4 in /opt/iobroker/node_modules/iobroker.landroid-s, node: v6.11.3
`

any idea how to resolve the issue?

**Comment by stefanpflug** [comment]
I think i have the same problem.
It seems that this crashes the ubuntu machine after 1-2 days because the vfs file-max-limit of the kernal is reached after a few hours.
lsof shows up thousands of filehandles to a pack file in the landroid folder owned by pm2 process.
Maybe it´s the same problem?

Updated Ubuntu twondays ago.

**Comment by migmailer** [comment]
Worx has updated their API version.

Install new ioBroker Landroid Adapter and its fine.
